import discord
from discord.ext import commands
from discord import app_commands
import os
from utils import *
from resources.constants import *

PARENT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
HOLY_SCRIPTURE_TXT = f"{PARENT_DIRECTORY}/resources/HolyScripture.txt"
USER_LEGEND_TXT = f"{PARENT_DIRECTORY}/resources/UserLegend.txt"

async def setup(bot: commands.Bot) -> None:
    await bot.add_cog(Text_Commands(bot))

class Text_Commands(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name = "yee", description = "My first application Command")
    async def yee(self, interaction: discord.Interaction):
        async with interaction.channel.typing():
            text = getYee()
        await interaction.channel.send(text)
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)


    @app_commands.command(name="ping", description="Check the bot's latency")
    async def ping(self, interaction: discord.Interaction):
        latency = interaction.latency * 1000
        await interaction.channel.send(f'Pong! Latency: {latency:.2f} ms')
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)


    @app_commands.command(name = "legend", description = "My first application Command")
    async def legend(self, interaction: discord.Interaction):        # Read in the user legend and print it. Maybe make this fancier later.
        async with interaction.channel.typing():
            with open(USER_LEGEND_TXT, "r", encoding="utf8") as userLegendFile:
                userLegendLines = userLegendFile.readlines()
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)
        await interaction.channel.send(''.join(userLegendLines))

    @app_commands.command(name = "roles", description = "My first application Command")
    async def roles(self, interaction: discord.Interaction):
        # Read in the Holy Scripture pertaining to our roles
        async with interaction.channel.typing():
            with open(HOLY_SCRIPTURE_TXT, "r", encoding="utf8") as holyScriptureFile:
                holyScriptureReading = ''.join(holyScriptureFile.readlines()[ENOS_START_LINE_NUMBER:(ENOS_START_LINE_NUMBER + ENOS_NUMBER_OF_LINES)])
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)
        await interaction.channel.send(holyScriptureReading + '\n' + 'These are our sacred roles & duties, as given by our Lord.')
        
    @app_commands.command(name = "yeee", description = "My first application Command")
    async def yeee(self, interaction: discord.Interaction):
        async with interaction.channel.typing():
            text = getYeee()
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)
        await interaction.channel.send(text)
        
    @app_commands.command(name = "helpplz", description = "My first application Command")
    async def helpplz(self, interaction: discord.Interaction):
        async with interaction.channel.typing():
            listOfCommands = LIST_OF_COMMANDS
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)
        await interaction.channel.send(''.join(listOfCommands))
        
    @app_commands.command(name = "wut", description = "My first application Command")
    async def wut(self, interaction: discord.Interaction):
        async with interaction.channel.typing():
            # Explain what this bot is about
            explanation = "I am an evangelist for YEEEEEEEEEEEEEEEEEE, the holy word we are commanded to proclaim by our Lord, Noah. This command can be found in Chapter 2 of our holy document, generated by a machine learning algorithm based on GPT-2, trained on a bdsm dataset scraped from Literotica, and fed sliding window prompts extracted from the King James Bible. For more information, see this link: https://www.reddit.com/r/MachineLearning/comments/fvwwzj/project_if_gpt2_read_erotica_what_would_be_its/"
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)
        await interaction.channel.send(explanation)

    @app_commands.command(name = "shem", description = "My first application Command")
    async def shem(self, interaction: discord.Interaction):
        async with interaction.channel.typing():
            text = getShem()
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)
        await interaction.channel.send(text)
        
    @app_commands.command(name = "shemm", description = "My first application Command")
    async def shemm(self, interaction: discord.Interaction):
        async with interaction.channel.typing():
            text = getShemm()
        await interaction.response.send_message('Wow you are so cool! ありがとう、パパ。', ephemeral=True)
        await interaction.channel.send(text)
    