# This is a basic workflow to help you get started with Actions

name: Deploy to ESXi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check for previous containers
        run: docker kill christotron && 0

      # - name: Build and Run Christotron
      #   uses: ./
      #   env:
      #     DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      - name: Build Christotron
        run: docker build . -t christotron:latest

      - name: Run Christotron
        run: docker run --name christotron -v "/var/run/docker.sock":"/var/run/docker.sock" --rm -e DISCORD_TOKEN christotron:latest
        env: 
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}

      # - uses: docker/build-push-action@v2
      #   with:
      #     tags: christotron:latest
      #     push: false

      # - uses: addnab/docker-run-action@v3
      #   with:
      #     image: christotron:latest
          # run: echo "hello world"
